### ISSUE TITLE
default value breakage

### ISSUE THREAD

**Issue by richardbowden** [goadesign/goa#2733] opened 2020-12-02 00:58 UTC
On updating to 3.2.5 the below code now fails to build.

the offending are is 

```
	Attribute("current", Boolean, "if true, this is the current user session", func() {
		Default(false)
	})
```

code gen works, but when you compile the project, we get the following error:

gen/user_management_service/service.go:136:19: invalid operation: vres.Current == zero (mismatched types *bool and bool)
gen/user_management_service/service.go:137:17: cannot use false (type bool) as type *bool in assignment

on looking at the last few changes for version 3.2.5, it looks like some pointer things were changed, but I cannot track it down....

removing `Default(false)` allow compile to work

```
package design

import (
	. "goa.design/goa/v3/dsl"
	_ "goa.design/plugins/v3/zerologger" // Enables the plugin
	
	// cors "goa.design/plugins/v3/cors/dsl"
	
)

var _ = API("UserAuth Management", func() {
	Title("UserAuth Management Service")
	Description("Creation, verification login and logout, profile and session management")
	Version("0.0.4")

	HTTP(func() {
		Path("api")
		Consumes("application/json")
		Produces("application/json")
	})

	Server("user_mgmt", func() {
		Services("User Management Service")

		Host("localdev", func() {
			Description("localhost used for development")
			URI("http://localhost:8000/api")
		})
	})
})

var _ = Service("User Management Service", func() {
	HTTP(func() {
		Path("user")
		Cookie("session_id:SID") // Load session ID from "SID" cookie
	})

	Method("active-sessions", func() {

		Result(CollectionOf(ActiveSessionMT))

		Payload(func() {
			Attribute("session_id", String, "Session ID")
			Required("session_id")
		})

		HTTP(func() {
			GET("active-sessions")
			Response(StatusOK)
			
		})
	})
})

var ActiveSessionMT = ResultType("application/vnd.paperpress.json", func() {
	TypeName("ActiveSessionResult")
	Description("an active session")
	Attribute("provider", String, "the provider the session is linked to")
	Attribute("email", String, "email address")
	Attribute("ip", String, "the ip where the user logged in from")
	Attribute("expires_at", String, "when the current session will expire")
	Attribute("session_ref", String, "the ref id of the session, this is not the session token")
	Attribute("user_agent", String, "the user agent of the client")
	Attribute("current", Boolean, "if true, this is the current user session", func() {
		Default(false)
	})
	Required("email", "expires_at", "session_ref")
})
```

**Comment by richardbowden** [comment] 2020-12-02 01:14
version 3.2.3 code generation

```
// newActiveSessionResultView projects result type ActiveSessionResult to
// projected type ActiveSessionResultView using the "default" view.
func newActiveSessionResultView(res *ActiveSessionResult) *usermanagementserviceviews.ActiveSessionResultView {
	vres := &usermanagementserviceviews.ActiveSessionResultView{
		Provider:   res.Provider,
		Email:      &res.Email,
		IP:         res.IP,
		ExpiresAt:  &res.ExpiresAt,
		SessionRef: &res.SessionRef,
		UserAgent:  res.UserAgent,
		Current:    &res.Current,
	}
	return vres
}
```

version 3.2.5 (FAILING) 

```
// newActiveSessionResultView projects result type ActiveSessionResult to
// projected type ActiveSessionResultView using the "default" view.
func newActiveSessionResultView(res *ActiveSessionResult) *usermanagementserviceviews.ActiveSessionResultView {
	vres := &usermanagementserviceviews.ActiveSessionResultView{
		Provider:   res.Provider,
		Email:      &res.Email,
		IP:         res.IP,
		ExpiresAt:  &res.ExpiresAt,
		SessionRef: &res.SessionRef,
		UserAgent:  res.UserAgent,
		Current:    &res.Current,
	}
	{
		var zero bool
		if vres.Current == zero {
			vres.Current = false
		}
	}
	return vres
}
```

**Comment by raphael** [comment] 2020-12-02 03:04
Thank you for the report, this does look like a bug.

**Comment by nitinmohan87** [comment] 2020-12-02 18:37
This bug is fixed in latest v3 code - https://github.com/goadesign/goa/issues/2707 . I can't reproduce it with latest v3. Probably just need to cut a new release?

**Closed as completed** 2022-02-06 06:07 UTC
Labels: bug
