### ISSUE TITLE
Use idiomatic Go names for `ID`, `API` and other acronyms in generated `app` code.

### ISSUE THREAD

**Issue by abourget** [goadesign/goa#306] opened 2016-02-21 05:52 UTC
Right now, `Attribute("backend_id")` produces `app` code with `BackendId` fields.

There is acronym support already in (https://github.com/goadesign/goa/blob/de9986a748f957c94c26af68218fb1f4a4c3b0b8/goagen/codegen/types.go#L249-L253), but it doesn't seem to be used in this case.

Let's also make sure we have a bunch of possible values in there, so we don't later break users' fields if we add some later.

**Comment by abourget** [comment] 2016-02-21 05:54
https://github.com/golang/lint/blob/master/lint.go#L702-L739 is the list in `go lint`

**Comment by abourget** [comment] 2016-02-21 05:55
This package does it, we can take inspiration there: https://godoc.org/github.com/serenize/snaker

It uses the same `go lint` initialisms list.

**Comment by moorereason** [comment] 2016-02-21 13:41
This is a dupe of #295

**Comment by bketelsen** [comment] 2016-02-22 15:16
can we close this dup?

**Comment by raphael** [comment] 2016-02-22 15:39
Yup, thank you

**Closed by raphael** 2016-02-22 15:39 UTC
