### ISSUE TITLE
How is 'Extend' supposed to work?

### ISSUE THREAD

**Issue by maxott** [goadesign/goa#2893] opened 2021-07-26 02:08 UTC
Hi,

I recently came across GOA and it looks like exactly what I was looking for. 

I started to use it for a simple API to learn more and ran into a few issues which are most likely due to my limited understanding of GOA as well as Go.

To limit repeating code, I wanted to take advantage of the `Expand` function. So I created two types where one is extending the other:

```
var HRefT = Type("HRefT", func() {
	Attribute("href", String, func() {
		Format(FormatURI)
		Example("https://api.com/foo/...")
		Meta("rpc:tag", "1")
	})
})

var RefT = Type("RefT", func() {
	Attribute("id", String, func() {
		Format(FormatUUID)
		Example("123e4567-e89b-12d3-a456-426614174000")
		Meta("rpc:tag", "2")
	})
	Extend(HRefT)
})
```

However, the generated code doesn't seem to reflect that.

`gen/xxx/service.go`
```
type HRefT struct {
	Href *string
}

type RefT struct {
	ID *string
}
```

Interestingly, the generated `openapi3.json` includes both a `RefT` as well as `RefT2`, with the latter only showing up in the `OpenAPI` specs.

```
"RefT": {
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "example": "123e4567-e89b-12d3-a456-426614174000",
      "format": "uuid"
    }
  },
  "example": {
    "id": "123e4567-e89b-12d3-a456-426614174000"
  }
},
"RefT2": {
  "type": "object",
  "properties": {
    "href": {
      "type": "string",
      "example": "https://api.com/foo/...",
      "format": "uri"
    },
    "id": {
      "type": "string",
      "example": "123e4567-e89b-12d3-a456-426614174000",
      "format": "uuid"
    }
  },
  "example": {
    "href": "https://api.com/foo/...",
    "id": "123e4567-e89b-12d3-a456-426614174000"
  }
},
```

What am I missing here?

**Comment by raphael** [comment] 2021-07-26 04:12
I am not able to reproduce the issue. Can you please provide a complete design together with a description of what code is expected in which file that differs with the generated code?

Using:
```go
package design

import . "goa.design/goa/v3/dsl"

var HRefT = Type("HRefT", func() {
        Attribute("href", String, func() {
                Format(FormatURI)
                Example("https://api.com/foo/...")
                Meta("rpc:tag", "1")
        })
})

var RefT = Type("RefT", func() {
        Attribute("id", String, func() {
                Format(FormatUUID)
                Example("123e4567-e89b-12d3-a456-426614174000")
                Meta("rpc:tag", "2")
        })
        Extend(HRefT)
})

var _ = Service("foo", func() {
        Method("bar", func() {
                Payload(RefT)
                HTTP(func() {
                        GET("/")
                })
        })
})
```
produces the file `gen/foo/service.go` with the following content (note the type definition in the end containing both fields):
```go
// Code generated by goa v3.4.3, DO NOT EDIT.
//
// foo service
//
// Command:
// $ goa gen extend/design

package foo

import (
        "context"
)

// Service is the foo service interface.
type Service interface {
        // Bar implements bar.
        Bar(context.Context, *RefT) (err error)
}

// ServiceName is the name of the service as defined in the design. This is the
// same value that is set in the endpoint request contexts under the ServiceKey
// key.
const ServiceName = "foo"

// MethodNames lists the service method names as defined in the design. These
// are the same values that are set in the endpoint request contexts under the
// MethodKey key.
var MethodNames = [1]string{"bar"}

// RefT is the payload type of the foo service bar method.
type RefT struct {
        ID   *string
        Href *string
}
```

**Comment by maxott** [comment] 2021-07-26 05:48
Thanks @raphael.

I think I found the problem, but not necessarily understand it.

If I use:
```
		Result(OrderListResultRT, func() {
			//View("tiny")
		})
```

I get in `gen/order/service.go`:

```
type RefT struct {
	ID *string
}
```

If I, however, replace that by:

```
		Result(OrderListResultRT)
```

it mysteriously changes to:

```
type RefT struct {
	ID   *string
	Href *string
}
```

Here is the full design file:

```
package design

import . "goa.design/goa/v3/dsl"

var _ = API("cre", func() {
	Server("cre", func() {
		Services("order")
		Host("localhost", func() {
			Description("default host")
			URI("http://localhost:8000")
			// URI("grpc://localhost:8080")
		})
	})
})

var _ = Service("order", func() {
	HTTP(func() {
		Path("/1/order")
	})

	Method("list", func() {
		Description("List all orders")
		Payload(func() {
		})

		Result(OrderListResultRT, func() {
			//View("tiny")
		})
		// Result(OrderListResultRT)
		HTTP(func() {
			GET("/")
			Response(StatusOK)
		})
	})
})

var OrderListResultRT = ResultType("application/vnd.cre.order.list", "OrderListRT", func() {
	Attributes(func() {
		Field(1, "orders", ArrayOf(listItemT), "Orders")
	})
})

var listItemT = Type("OrderListItem", func() {
	Field(1, "name", String, "Optional customer provided name", func() {
		Example("Fire risk for Lot2")
	})
	Field(2, "status", String, "Order status", func() {
		Enum("pending", "executing", "finished", "error")
	})
	Field(3, "links", RefT)
})

var HRefT = Type("HRefT", func() {
	Attribute("href", String, func() {
		Format(FormatURI)
		Example("https://api.com/foo/...")
		Meta("rpc:tag", "1")
	})
})

var RefT = Type("RefT", func() {
	Attribute("id", String, func() {
		Format(FormatUUID)
		Example("123e4567-e89b-12d3-a456-426614174000")
		Meta("rpc:tag", "2")
	})
	Extend(HRefT)
})
```

**Comment by maxott** [comment] 2021-07-26 05:49
BTW, I'm using `Goa version v3.4.3`

**Comment by raphael** [comment] 2021-07-28 05:37
Thank you for the info, that looks like a bug - I'll take a look.

**Comment by raphael** [comment] 2021-08-16 04:25
This is now fixed, thank you for the great repro!

**Closed as completed** 2021-08-16 04:24 UTC
