### ISSUE TITLE
Errors are not being sent in actual JSON

### ISSUE THREAD

**Issue by thecodethinker** [goadesign/goa#343] opened 2016-03-07 23:01 UTC
I've noticed that when an `InvalidParamTypeError` is launched goa returns this

`"[{\"id\":1,\"title\":\"invalid parameter value\",\"msg\":\"invalid value \\\"cfvbn\\\" for parameter \\\"right\\\", must be a integer\"}]"`

instead of actual, correctly formatted JSON. I changed the `Content-Type` header of the responses to `application/json` but that didn't change this issue.
I've been digging around the code but I can't see where this is getting sent.

**Comment by raphael** [comment] 2016-03-07 23:07
There's already an open issue for this, closing as duplicate of #285

**Closed by raphael** 2016-03-07 23:07 UTC
