### ISSUE TITLE
Issue with dep init

### ISSUE THREAD

**Issue by kumarsiva07** [goadesign/goa#1515] opened 2018-01-31 06:45 UTC
Cloned the example design and ran dep init and tried to run goa gen command.
I got the below error
```
exit status 1
design must define at least one service
```
https://gitlab.com/kossaka/goa-example/tree/master

**Comment by raphael** [comment] 2018-01-31 19:14
I'm not able to repro, can you provide the exact steps you are using?
```
 ~/g/s/g/r/junk  git clone https://gitlab.com/kossaka/goa-example
Cloning into 'goa-example'...
warning: redirecting to https://gitlab.com/kossaka/goa-example.git/
remote: Counting objects: 88, done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 88 (delta 31), reused 0 (delta 0)
Unpacking objects: 100% (88/88), done.
 ~/g/s/g/r/junk  cd goa-example        1139ms  Wed 31 Jan 2018 11:10:17 AM PST
 ~/g/s/g/r/j/goa-example   master  dep init   Wed 31 Jan 2018 11:10:21 AM PST
  Locking in master (795b5e3) for transitive dep github.com/zach-klippenstein/goregen
  Locking in v5.0.0 (8cc36ee) for transitive dep github.com/dimfeld/httptreemux
  Locking in master (3dbebcf) for transitive dep golang.org/x/sys
  Locking in v1.0.0 (1744e29) for transitive dep github.com/sergi/go-diff
  Locking in master (ee938bf) for transitive dep github.com/dimfeld/httppath
  Using ^1.3.1 as constraint for direct dep github.com/boltdb/bolt
  Locking in v1.3.1 (2f1ce7a) for direct dep github.com/boltdb/bolt
  Locking in master (25101aa) for transitive dep golang.org/x/tools
  Using master as constraint for direct dep goa.design/plugins
  Locking in master (9a3b883) for direct dep goa.design/plugins
  Using master as constraint for direct dep goa.design/goa
  Locking in master (4b0bddb) for direct dep goa.design/goa
  Locking in master (9fbc68a) for transitive dep github.com/manveru/faker
 ~/g/s/g/r/j/goa-example   master …  goa gen github.com/raphael/junk/goa-example/cellar/design             Wed 31 Jan 2018 11:11:27 AM PST
gen/child/client.go
gen/child/endpoints.go
gen/child/service.go
gen/http/child/client/cli.go
...
```

**Comment by kumarsiva07** [comment] 2018-02-02 12:07
Update you dep.
```
goa gen goa.design/goa/examples/cellar/design
exit status 1
design must define at least one service
```

I am getting our example also

**Comment by raphael** [comment] 2018-02-10 20:04
I'm closing this issue as I'm not able to reproduce it.

**Closed by raphael** 2018-02-10 20:04 UTC

**Comment by jpudney** [comment] 2018-02-20 16:58
@raphael I've been able to replicate the above with the following:

```
~/P/src> git clone https://gitlab.com/kossaka/goa-example gitlab.com/kossaka/goa-example
Cloning into 'gitlab.com/kossaka/goa-example'...
remote: Counting objects: 88, done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 88 (delta 31), reused 0 (delta 0)
Receiving objects: 100% (88/88), 35.40 KiB | 381.00 KiB/s, done.
Resolving deltas: 100% (31/31), done.
~/P/src> cd gitlab.com/kossaka/goa-example/cellar
~/P/s/g/k/goa-example> dep ensure
could not find project Gopkg.toml, use dep init to initiate a manifest
~/P/s/g/k/g/cellar> ls -al
total 56
-rw-r--r--  1 james  staff   2.4K 20 Feb 16:51 Gopkg.lock
-rw-r--r--  1 james  staff   864B 20 Feb 16:51 Gopkg.toml
drwxr-xr-x  4 james  staff   128B 20 Feb 16:51 cmd
-rw-r--r--  1 james  staff   2.7K 20 Feb 16:51 db.go
drwxr-xr-x  8 james  staff   256B 20 Feb 16:51 design
drwxr-xr-x  6 james  staff   192B 20 Feb 16:51 gen
-rwxr-xr-x  1 james  staff   178B 20 Feb 16:51 launch.sh
-rw-r--r--  1 james  staff   653B 20 Feb 16:51 sommelier.go
-rw-r--r--  1 james  staff   2.5K 20 Feb 16:51 storage.go
-rw-r--r--  1 james  staff   387B 20 Feb 16:51 swagger.go
~/P/s/g/k/g/cellar> dep ensure
dep: WARNING: Unknown field in manifest: prune
~/P/s/g/k/g/cellar> pwd
/Users/james/Projects/src/gitlab.com/kossaka/goa-example/cellar
~/P/s/g/k/g/cellar> ls -al
total 56
drwxr-xr-x  13 james  staff   416 20 Feb 16:52 .
drwxr-xr-x   5 james  staff   160 20 Feb 16:51 ..
-rw-r--r--   1 james  staff  2307 20 Feb 16:52 Gopkg.lock
-rw-r--r--   1 james  staff   864 20 Feb 16:51 Gopkg.toml
drwxr-xr-x   4 james  staff   128 20 Feb 16:51 cmd
-rw-r--r--   1 james  staff  2725 20 Feb 16:51 db.go
drwxr-xr-x   8 james  staff   256 20 Feb 16:51 design
drwxr-xr-x   2 james  staff    64 20 Feb 16:52 gen
-rwxr-xr-x   1 james  staff   178 20 Feb 16:51 launch.sh
-rw-r--r--   1 james  staff   653 20 Feb 16:51 sommelier.go
-rw-r--r--   1 james  staff  2604 20 Feb 16:51 storage.go
-rw-r--r--   1 james  staff   387 20 Feb 16:51 swagger.go
drwxr-xr-x   5 james  staff   160 20 Feb 16:52 vendor
~/P/s/g/k/g/cellar> goa gen gitlab.com/kossaka/goa-example/cellar
exit status 1
design must define at least one service
```

It seems that if there's a `vendor` directory then the `goa gen` command fails.

**Comment by dgaedcke** [comment] 2018-03-01 14:57
two of us are getting this exact same issue;   the other guy is a VERY SR. Go developer & he can't figure it out either....

does it possibly have anything to do with GAE projects (where main.go is not at the top level ??)

**Comment by raphael** [comment] 2018-03-01 17:29
The error seems to indicate that the `goa.design/goa/design` package that was used by the `goa` tool to build the final (temporary) code generator tool was different from the one imported by your design. I'm guessing one is using the vendored version and one isn't. You might have to compile the goa tool in the vendor directory and use that one to generate the code.

**Comment by dgaedcke** [comment] 2018-03-01 17:56
that sounds right!
so I've been using:
cd /Users/dgaedcke/dev/gocode/src/goa.design/goa
git pull

to upgrade to GOA V2
I'm guessing Dep was vendoring a different version??

What is the recommended way to stay up to date with V2

**Comment by kumarsiva07** [comment] 2018-03-18 05:52
![image](https://user-images.githubusercontent.com/7725174/37563072-7d530ac2-2a9e-11e8-9901-32af00213f80.png)
Add `required = ["goa.design/goa/codegen/generator"]` in Gopkg.toml

**Comment by mnoster** [comment] 2019-02-03 00:01
I encountered the same issue and resolved it by:
1.)  `required = ["goa.design/goa/codegen/generator"] in Gopkg.toml`
2.) `dep ensure -update`
