### ISSUE TITLE
Not matching checksum for 3.0.7

### ISSUE THREAD

**Issue by ilmaruk** [goadesign/goa#2378] opened 2019-11-14 12:41 UTC
The checksum for v3.0.7 doesn't seem to match that of sum.golang.org.

```
$ go get goa.design/goa/v3
verifying goa.design/goa/v3@v3.0.7/go.mod: checksum mismatch
	downloaded: h1:LBOZJ4IG44oG7RBu6R3oLpRo95Y4e4AFi2JHwl0EsSo=
	sum.golang.org: h1:sEWV8VRLZenziAnHcIHjjGvlC2pwEvNblwBtMuyPwqQ=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

Could you please check?

**Comment by raphael** [comment] 2019-11-14 16:12
Hmm strange the checksum isn't something that comes from the repo... Have you tried removing the local copy of `go.sum`?

**Comment by Yvonne2017** [comment] 2019-11-26 05:31
@raphael, I have seen the same issue as well.

**Comment by raphael** [comment] 2019-11-27 22:56
This has been reported by others as well. I wonder if it's related to https://github.com/golang/go/issues/34065 - basically different versions of the Go compiler could generate different checksums (versions 1.11.4 and older vs newer). Try deleting your `$GOPATH/pkpg/mod/cache` and see whether that fixes it.

**Comment by raphael** [comment] 2019-12-12 04:49
Closing this issue, v3.0.8 has been released and I can't reproduced the issue.

**Closed as completed by raphael** 2019-12-12 04:49 UTC
