### ISSUE TITLE
JSON response omitting empty collections

### ISSUE THREAD

**Issue by jim-slattery-rs** [goadesign/goa#288] opened 2016-02-11 21:00 UTC
We have a MediaType that contains:
```go
Attributes(func() {
	Attribute("roles", CollectionOf(RoleRefMediaType))
})
Links(func() {
	Link("roles")
})
```
But the generated code looks like this:
```go
type RoleReportLinks struct {
	Roles ReferenceRoleLinkCollection `json:"roles,omitempty" xml:"roles,omitempty"`
}
```
Notice the `omitempty` flag is present. So there doesn't seem to be a way for our responses to include an empty roles list, like this:
```json
{"roles":[]}
```

Blindly tried adding `Required(...)` in a few places, but `omitempty` wouldn't budge:
```go
Attributes(func() {
	Attribute("roles", CollectionOf(RoleRefMediaType))
	Required("roles")
})
Links(func() {
	Link("roles")
	Required("roles")
})
View("default", func() {
	Attribute("links")
	Required("links")
})
```
Maybe `CollectionOf` is creating a new type that is not "required"?

**Comment by raphael** [comment] 2016-03-29 05:04
@jim-slattery-rs I'm not able to reproduce the problem with the latest, can you confirm whether the issue is fixed and if not provide a complete design to repro? thanks!

**Comment by raphael** [comment] 2016-04-06 03:26
Closing this, reopen if needed.

**Closed by raphael** 2016-04-06 03:26 UTC
Labels: bug
