### ISSUE TITLE
Generated validation code in test function doesn't return proper type (JSONAPI)

### ISSUE THREAD

**Issue by kwk** [goadesign/goa#898] opened 2016-11-21 09:33 UTC
Hi,

I've successfully implemented a few endpoints using JSONAPI in our current API. You can find my design folder here: https://github.com/kwk/almighty-core/tree/fix-322/design

Everything works fine except one thing: returning [JSONAPI errors](http://jsonapi.org/format/#errors). I have defined a `JSONAPIErrors` media type [here](https://github.com/kwk/almighty-core/blob/868fdf848e9ca6e6dc430a77be1729f09a904b68/design/media_types.go#L227):

```go
// JSONAPIErrors is an array of JSONAPI error objects
var JSONAPIErrors = a.MediaType("application/vnd.jsonapierrors+json", func() {
	a.ContentType("application/vnd.api+json")
	a.TypeName("JSONAPIErrors")
	a.Description(``)
	a.Attributes(func() {
		a.Attribute("errors", a.ArrayOf(JSONAPIError))
		a.Required("errors")
	})
	a.View("default", func() {
		a.Attribute("errors")
		a.Required("errors")
	})
})
```

The [`show` action](https://github.com/kwk/almighty-core/blob/868fdf848e9ca6e6dc430a77be1729f09a904b68/design/resources.go#L444) of the `work-item-link-category` resource defines a few responses that return the afore mentioned media type:

```go
	a.Action("show", func() {
		a.Routing(
			a.GET("/:id"),
		)
		a.Description("Retrieve work item link category (as JSONAPI) for the given ID.")
		a.Params(func() {
			a.Param("id", d.String, "ID of the work item link category")
		})
		a.Response(d.OK, func() {
			a.Media(WorkItemLinkCategory)
		})
		a.Response(d.BadRequest, func() {
			a.Media(JSONAPIErrors)
		})
		a.Response(d.InternalServerError, func() {
			a.Media(JSONAPIErrors)
		})
		a.Response(d.NotFound, func() {
			a.Media(JSONAPIErrors)
		})
	})
```

When I generate the app code from this design, I get this test function for example:

```go
func CreateWorkItemLinkCategoryBadRequest(t goatest.TInterface, ctx context.Context, service *goa.Service, ctrl app.WorkItemLinkCategoryController, payload *app.CreateWorkItemLinkCategoryPayload) (http.ResponseWriter, *app.JSONAPIErrors) {
	// Setup service
	var (
		logBuf bytes.Buffer
		resp   interface{}

		respSetter goatest.ResponseSetterFunc = func(r interface{}) { resp = r }
	)
	if service == nil {
		service = goatest.Service(&logBuf, respSetter)
	} else {
		logger := log.New(&logBuf, "", log.Ltime)
		service.WithLogger(goa.NewLogger(logger))
		newEncoder := func(io.Writer) goa.Encoder { return respSetter }
		service.Encoder = goa.NewHTTPEncoder() // Make sure the code ends up using this decoder
		service.Encoder.Register(newEncoder, "*/*")
	}

	// Validate payload
	err := payload.Validate()
	if err != nil {
		e, ok := err.(goa.ServiceError)
		if !ok {
			panic(err) // bug
		}
		if e.ResponseStatus() != 400 {
			t.Errorf("unexpected payload validation error: %+v", e)
		}
		return nil, e
	}

	// Setup request context
	rw := httptest.NewRecorder()
	u := &url.URL{
		Path: fmt.Sprintf("/api/workitemlinkcategories"),
	}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		panic("invalid test " + err.Error()) // bug
	}
	prms := url.Values{}
	if ctx == nil {
		ctx = context.Background()
	}
	goaCtx := goa.NewContext(goa.WithAction(ctx, "WorkItemLinkCategoryTest"), rw, req, prms)
	createCtx, err := app.NewCreateWorkItemLinkCategoryContext(goaCtx, service)
	if err != nil {
		panic("invalid test data " + err.Error()) // bug
	}
	createCtx.Payload = payload

	// Perform action
	err = ctrl.Create(createCtx)

	// Validate response
	if err != nil {
		t.Fatalf("controller returned %s, logs:\n%s", err, logBuf.String())
	}
	if rw.Code != 400 {
		t.Errorf("invalid response status code: got %+v, expected 400", rw.Code)
	}
	var mt *app.JSONAPIErrors
	if resp != nil {
		var ok bool
		mt, ok = resp.(*app.JSONAPIErrors)
		if !ok {
			t.Fatalf("invalid response media: got %+v, expected instance of app.JSONAPIErrors", resp)
		}
		err = mt.Validate()
		if err != nil {
			t.Errorf("invalid response media type: %s", err)
		}
	}

	// Return results
	return rw, mt
}
```

Please notice, that the second response type is ` *app.JSONAPIErrors` as I expected it to be. But there's a problem with the code that does the validation and returns a `goa.ServiceError` instead of a `*app.JSONAPIErrors`.

```go
	// Validate payload
	err := payload.Validate()
	if err != nil {
		e, ok := err.(goa.ServiceError)
		if !ok {
			panic(err) // bug
		}
		if e.ResponseStatus() != 400 {
			t.Errorf("unexpected payload validation error: %+v", e)
		}
		return nil, e
	}
```

The line `return nil,e` causes the code to not compile:

```
app/test/work-item-link-category_testing.go:61: cannot use e (type goa.ServiceError) as type *app.JSONAPIErrors in return argument
```

Am I doing something wrong or how can I get the code to return a proper JSONAPI error?

Btw. I've also overwritten the standard `ErrorHandler` with [my own JSONAPI error handler](https://github.com/kwk/almighty-core/blob/868fdf848e9ca6e6dc430a77be1729f09a904b68/jsonapi/error_handler.go) which can [convert](https://github.com/kwk/almighty-core/blob/fix-322/jsonapi/jsonapi_utility.go#L26) our own errors as well as `goa.ServiceError`s to JSONAPI errors.

I'd love to hear what I can do or if there are any problems with the [generation code](https://github.com/goadesign/goa/blob/9aa9c0c0c434d2ae15ccabbbbfa3a9e8e843812b/goagen/gen_app/test_generator.go#L305).

Thank you in advance!

PS: The issue #567 also deal with JSONAPI.

**Comment by tsmaeder** [comment] 2016-11-21 14:28
I was able to make the code generate ok with by replacing line 313 in goagen/gen_app/test_generator.go with the following:
```
{{ if $test.ReturnType }}return nil, nil {{ else }}return nil{{ end }}
```

**Comment by raphael** [comment] 2016-11-21 16:19
I actually pushed a fix for this last night. This issue is a duplicate of #883.

**Closed by raphael** 2016-11-21 16:19 UTC

**Comment by kwk** [comment] 2016-11-21 16:23
@raphael Yes I saw it but this change introduced another bug which I hope gets fixed with my PR https://github.com/goadesign/goa/pull/900

**Comment by raphael** [comment] 2016-11-21 16:28
OK thank you.
