### ISSUE TITLE
CORS headers not added to swagger.json response

### ISSUE THREAD

**Issue by jimmidyson** [goadesign/goa#461] opened 2016-05-04 22:37 UTC
With `Origin("*", func() {...` in the API definition, CORS headers are added correctly to API responses but are not added to the /swagger.json response. This makes it trickier to use Swagger UI for API discovery & browsing, as well as dynamic client generation, etc.

**Comment by raphael** [comment] 2016-05-04 22:51
The problem is that the service `ServeFiles` method is not hooked up to the generated CORS middleware. This middleware is generated as a private function of the `app` package at the moment so you can't hook it up yourself either. Two things need to change:

1. The generated CORS middlewares should be public functions
2. The generated Swagger controller should take advantage of these functions when they exist (that is when the design specifies a CORS specification).

There should also be clear documentation around that. Thank you for bringing this up!

**Comment by raphael** [comment] 2016-05-16 00:05
Fixed by #490 - Does require changing the design, please read the comments in the PR.

**Closed by raphael** 2016-05-16 00:05 UTC
Labels: bug
