### ISSUE TITLE
Generated Client Code required parameters get generated as pointers on 'id' abbr

### ISSUE THREAD

**Issue by advanderveer** [goadesign/goa#524] opened 2016-06-04 09:08 UTC
Currently, the following design

```Go
// user
var _ = Resource("user", func() {
	Action("delete", func() {
		Routing(DELETE("/user"))
		Description("delete an existing user")
		Params(func() {
			Param("userId", String, "the email address of the new user")
			Required("userId")
		})
		Response(NotFound)
		Response(NoContent)
	})
})
```

will generate the following signature in the generated client code (the pointer type for userId is unexpected)

```Go
func (c *Client) NewDeleteUserRequest(ctx context.Context, path string, userID *string) (*http.Request, error) 
```

while the generated context is correct:

```Go
// DeleteUserContext provides the user delete action context.
type DeleteUserContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Service *goa.Service
	UserID  string
}
```

changing the spec to the following fixes the "NewRequest" signature

```Go
// user
var _ = Resource("user", func() {
	Action("delete", func() {
		Routing(DELETE("/user"))
		Description("delete an existing user")
		Params(func() {
			Param("userId", String, "the email address of the new user")
			Required("userID") //@this fixes the generated client code
		})
		Response(NotFound)
		Response(NoContent)
	})
})

```

but will break the request context

**Comment by advanderveer** [comment] 2016-06-04 12:09
Specifying the paramter in the rougint correctly will fix this problem, e.i:

```go
	Action("delete", func() {
		Routing(DELETE("/user/:userId")) //@use userId here as well
		Description("delete an existing user")
		Params(func() {
			Param("userId", String, "the id of an existing user", func() { Pattern("^[a-zA-Z0-9-]+$") })
			Required("userId")
		})
		Response(NotFound)
		Response(NoContent)
	})
```
probably not a bug, feel free to reopen if it is

**Comment by raphael** [comment] 2016-06-04 18:57
The current behavior consists of generating optional string params for parameters used in routes but not explicitly defined. It could be debated whether that's helpful or prone to cause unexpected behavior though :)

**Comment by advanderveer** [comment] 2016-06-08 08:08
I ran into another usecase were I do feel the behaviour is a bug, not sure if I explained it correctly. The unexpected behaviour comes from the mismatch of generated signatures between the client and context signatures. Lets consider an endpoint with that looks like the following

`POST /project/:projectId/run?baseId=:planId` so new 'runs' can be created based on a 'plan' that must be provided but is not an attribute of the newly created 'run' . A design would look like the following: 

```Go
var _ = Resource("run", func() {
	Action("create", func() {
		Routing(POST("/project/:projectId/run"))
		Description("create a new run for a project")
		Params(func() {
			Param("projectId", String, "ID of an existing project", func() { Pattern("^[a-zA-Z0-9-]+$") })
			Param("planId", String, "ID of a preconfigured plan on which the run is based", func() { Pattern("^[a-zA-Z0-9-]+$") })
			Required("planId")
		})

		Response(NotFound)
		Response(OK, RunMedia)
	})
})
```

In the controller I can retrieve the 'planId' as expected e.g: 

```Go
func (ctrl *RunCtrl) Create(ctx *app.CreateRunContext) error {
     planID = ctx.PlanID //retrieving the planId query param
}
```

But in my tests, when I attempt to create an request using the generated client:

```Go
resp, err := apic.CreateRun(ctx, v1client.CreateRunPath(projectID), &planID)
...
```

the request will fail with a message like "missing required parameter "planId", if we look at the generated client code we can see why: 

```Go
func (c *Client) NewCreateRunRequest(ctx context.Context, path string, planID string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	values.Set("planID", planID) //we see it sets 'planID' instead of 'planId'
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	c.JWTSigner.Sign(ctx, req)
	return req, nil
}
```

note the comment; the ID part of the query param seems to be wrongly generated. Let me know if i'm missing something!

**Comment by raphael** [comment] 2016-06-11 19:24
Ah yes that looks like a genuine bug, thank you!

**Comment by raphael** [comment] 2016-06-12 05:20
Which is actually already fixed :) 
Closing again.

**Closed by raphael** 2016-06-12 05:20 UTC
Labels: bug

**Comment by dhrp** [comment] 2016-07-02 00:45
I'm getting similar unexpected mismatches on type.

* If the paramater is required it is a value, 
* if it's not required you get a pointer. 
* If the value is UserId it will be turned into UserID 

To me this is very confusing.

```
Params(func() {
    Param("userId", String, "User")
    Param("knownLocation", String, "blah")
        Required("userId", "knownLocation")
})

results in 

// SetKnownLocationLocationContext provides the location setKnownLocation action context.
type SetKnownLocationLocationContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	KnownLocation string
	UserID        string
}

whereas:

Params(func() {
    Param("userId", String, "User")
    Param("knownLocation", String, "blah")
    //    Required("userId", "knownLocation") (nothing required)
})

results in:

// SetKnownLocationLocationContext provides the location setKnownLocation action context.
type SetKnownLocationLocationContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	KnownLocation *string
	UserID        *string

and 


Params(func() {
    Param("userId", String, "User")
    Param("knownLocation", String, "blah")
        Required("userID", "knownLocation") (userID spelled like with capitals)
})

results in:

// SetKnownLocationLocationContext provides the location setKnownLocation action context.
type SetKnownLocationLocationContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	KnownLocation string
	UserID        *string


```

**Comment by raphael** [comment] 2016-07-02 00:54
This is by design:

* Required parameters can never be nil, the generated validation codes makes sure of that. As a user of the generated code it's much more convenient to deal with `string` than `*string`.

* Optional parameters - by definition - can be nil so using `string` would not work, the controller code needs to be able to make the distinction between `""` and `nil` (to keep with the string example, this is even worse with e.g. `int` for example where the zero value is `0`)

As for the name "changing": the name in the design is just that: the name used by the design to refer to this attribute. This name is reflected in the documentation and possibly in generated comments. 

When generating source code though the corresponding identifiers needs to follow the language rules and conventions. `goagen` uses [this algorithm](https://github.com/goadesign/goa/blob/e80aa8f771146fc709fba146571e1d31803fb6b9/goagen/codegen/types.go#L360) to generate valid Go identifiers from design names.

The reason the last example behaves the way it does is because in the design `UserId` and `UserID` are different names referring to different things (actually `goagen` should complain that there is no corresponding attribute to the required validation - looks like there may be a bug there).
