### ISSUE TITLE
err declared but never used in `BuildGetPayload` func

### ISSUE THREAD

**Issue by seward** [goadesign/goa#2154] opened 2019-06-18 18:33 UTC
I’m getting build errors on my generated `http/my_resource/client/cli.go` file in the `BuildGetPayload` func like `err declared but never used`. I think this is a bug in the codegen.

Using goa version v2.0.0-wip.

Here’s my resource DSL:
```
Service("ourGreatResource", func() {
    Description("Our great resource!")
    // Specifies the error responses that all endpoints could return.
    OurCustomErrorsPlugin()

    Method("get", func() {
        Description("GET /goa/resource")

        GraphQLQuery(graphql.GetResourceQuery, graphql.GqlOrgIdEndDurationMsArgsRequest{}, graphql.GqlGetResourceResponse{})

        Payload(models.GetResourceRequest)

        Result(models.GetResourceResponse)

        HTTP(func() {
            GET("/goa/resource")
            Param("durationMs")
            Param("endMs")
            Response(StatusOK, func() {
                Description("Returns the fetched resources from most recent to least recent.")
            })
        })
    })
})
```

**Comment by nitinmohan87** [comment] 2019-06-19 17:29
@seward You seem to be using an old pre-release version of goa v2. We have released [goa v3](https://goa.design/blog/009-v_3_0_0/) with go modules support and goa v2 if you don't use go modules. Could you please update goa to one of these released versions and see if you are running into this issue again?

**Comment by seward** [comment] 2019-06-19 19:45
> @seward You seem to be using an old pre-release version of goa v2. We have released [goa v3](https://goa.design/blog/009-v_3_0_0/) with go modules support and goa v2 if you don't use go modules. Could you please update goa to one of these released versions and see if you are running into this issue again?

I'm on revision `de50fdd`, which looks like the same as the `v2.0.0` release?

**Comment by nitinmohan87** [comment] 2019-06-19 23:14
`de50fdd` is the latest v2 release. I was thrown off when you indicated you were using `v2.0.0-wip`. However, I am not able to reproduce the error you are getting. Would it be possible to provide the attributes in the payload type `models.GetResourceRequest` that would reproduce this error? It is kind of difficult to debug without that.

**Comment by nitinmohan87** [comment] 2019-07-19 17:39
Closing this issue as it is not reproducible. Please feel free to reopen it if you encounter the bug again and provide a design that reproduces this issue.

**Closed as completed by nitinmohan87** 2019-07-19 17:39 UTC
Labels: need more info
