### ISSUE TITLE
V3: go build not working for service using file servers

### ISSUE THREAD

**Issue by SantoshSah** [goadesign/goa#2176] opened 2019-07-03 11:19 UTC
I am following https://github.com/goadesign/plugins/tree/v3/goakit. `goakit` is generating files as mentioned in above doc but `go build` is not working and throwing error `cmd/calc/main.go:4:2: found packages calcapi (calc.go) and calc (openapi.go) in [project_path]`.

**Comment by raphael** [comment] 2019-07-03 16:36
This problem is actually not specific to goakit, here is a repro design:
```go
package design

import . "goa.design/goa/v3/dsl"

// API describes the global properties of the API server.
var _ = API("calc", func() {
	Title("Calculator Service")
	Description("HTTP service for adding numbers, a goa teaser")
	Server("calc", func() {
		Host("localhost", func() { URI("http://localhost:8088") })
	})
})

// Service describes a service
var _ = Service("calc", func() {
	Description("The calc service performs operations on numbers")
	// Method describes a service method (endpoint)
	Method("add", func() {
		// Payload describes the method payload
		// Here the payload is an object that consists of two fields
		Payload(func() {
			// Attribute describes an object field
			Attribute("a", Int, "Left operand")
			Attribute("b", Int, "Right operand")
			// Both attributes must be provided when invoking "add"
			Required("a", "b")
		})
		// Result describes the method result
		// Here the result is a simple integer value
		Result(Int)
		// HTTP describes the HTTP transport mapping
		HTTP(func() {
			// Requests to the service consist of HTTP GET requests
			// The payload fields are encoded as path parameters
			GET("/add/{a}/{b}")
			// Responses use a "200 OK" HTTP status
			// The result is encoded in the response body
			Response(StatusOK)
		})
	})
})

var _ = Service("openapi", func() {
	// Serve the file with relative path ../../gen/http/openapi.json for
	// requests sent to /swagger.json.
	Files("/swagger.json", "../../gen/http/openapi.json")
})
```

**Comment by ikawaha** [comment] 2019-07-07 03:44
This bug fixed in #2172  (commit 85024ebc66dceefda0250f07a07e4a8a441f2e3d66f). However, even if this commit number is specified in goa of the project's go.mod file, it can not be confirmed.
Because `goa gen` will overwrite the go.mod file. (see #2181 )

The following steps are required to confirm that this has been fixed.
* git clone goa and make it up-to-date
* specify `replace` that repository in go.mod file
* goa gen / goa example

### Example

```shellsession
$ more go.mod
module calc

go 1.12

replace goa.design/goa/v3 => ../../../goa.design/goa

require goa.design/goa/v3 v3.0.2
$ goa gen calc/design
...snip...
$ goa example calc/design
calc.go
cmd/calc-cli/http.go
cmd/calc-cli/main.go
cmd/calc/http.go
cmd/calc/main.go
openapi.go
$ ls *.go|xargs head -1
==> calc.go <==
package calcapi

==> openapi.go <==
package calcapi
```

**Comment by SantoshSah** [comment] 2019-07-07 14:01
@ikawaha , thank you. What we need to change in `calc` example to make it work?

**Comment by ikawaha** [comment] 2019-07-10 04:47
There is no need to change anything in `calc` because it is a bug in goa.
Now that ~~#2191~~ #2181 has been merged, I wonder you can try it with the following steps:

1. go get -u goa.design/goa/v3/...@59098d18e1ec3674d11feb5a716f5f165c052835
1. (rm -rf  *.go ./cmd)
1. goa gen calc/design
1. goa example calc/design

**Comment by jamesrom** [comment] 2019-07-10 05:25
@ikawaha #2191 has not been merged

**Comment by ikawaha** [comment] 2019-07-10 05:37
@jamesrom Sorry. It's typo. #2191  -> #2181

**Comment by raphael** [comment] 2019-07-22 02:26
I can confirm this is fixed, thank you @ikawaha.

**Closed as completed by raphael** 2019-07-22 02:26 UTC
Labels: bug
