### ISSUE TITLE
issue with struct tag and with the multiple custom type

### ISSUE THREAD

**Issue by lockwobr** [goadesign/goa#2942] opened 2021-10-22 22:22 UTC
I do not know any good way to explain this issue but to make an example of it, so that is what I did. https://github.com/lockwobr/goa-example-multi-type

If you have the same custom type nested more than once at the same level and you struct tag in the meta then the api results will omit those fields. It you have just one than it returns data in this example, but the tags are not working, seem to be ignored. I have found a way around this to make a new type for each time you have to repeat of the inner nested type, but sucks to repeat yourself when they are the same type.

Here is the example from the repo: `/family` endpoint is the example of nested types with struct tags
```
package design

import (
	. "goa.design/goa/v3/dsl"
)

var _ = API("exmp", func() {
	Title("example Service")

	Server("exmp", func() {
		Services("exmp")
		Host("development", func() {
			URI("http://localhost:9000/")
		})

	})
})

var _ = Service("exmp", func() {

	Method("get-person", func() {
		HTTP(func() {
			GET("/person")
			Response(StatusOK)
		})
		Result(person)
	})
	Method("get-fam", func() {
		HTTP(func() {
			GET("/family")
			Response(StatusOK)
		})
		Result(family)
	})
})

var person = ResultType("application/person", "person", func() {
	Attribute("name", String, func() {
		Meta("struct:tag:json", "first_name")
	})
	Attribute("age", Int)
})

var family = ResultType("application/family", "fam", func() {
	Attribute("surname", String)
	Attribute("size", Int)
	Attribute("mother", person, func() {
		Meta("struct:tag:json", "mom") // if you comment one of these out it works, but having tags on both breaks the api output
	})
	Attribute("father", person, func() {
		Meta("struct:tag:json", "dad")
	})
	Attribute("kids", ArrayOf(person))
})
```

**Comment by raphael** [comment] 2021-10-24 21:31
Thank you for providing a nice repro. The behavior is by design: the attributes are not required and thus omitted when empty by the data structure generated by default by Goa:
```go
type GetFamResponseBody struct {
	Surname *string               `form:"surname,omitempty" json:"surname,omitempty" xml:"surname,omitempty"`
	Size    *int                  `form:"size,omitempty" json:"size,omitempty" xml:"size,omitempty"`
	Mother  *PersonResponseBody   `form:"mother,omitempty" json:"mother,omitempty" xml:"mother,omitempty"`
	Father  *PersonResponseBody   `form:"father,omitempty" json:"father,omitempty" xml:"father,omitempty"`
	Kids    []*PersonResponseBody `form:"kids,omitempty" json:"kids,omitempty" xml:"kids,omitempty"`
}
``` 
Providing the json tag in the design overrides the above and instead produces:
```go
type GetFamResponseBody struct {
	Surname *string               `form:"surname,omitempty" json:"surname,omitempty" xml:"surname,omitempty"`
	Size    *int                  `form:"size,omitempty" json:"size,omitempty" xml:"size,omitempty"`
	Mother  *PersonResponseBody   `json:"mom"`
	Father  *PersonResponseBody   `json:"dad"`
	Kids    []*PersonResponseBody `form:"kids,omitempty" json:"kids,omitempty" xml:"kids,omitempty"`
}
```
There is no `omitempty` tag meaning that the fields will be generated even if the values are `nil`. So to get the same behavior in both cases either make the attributes required (in which case Goa won't generate a `omitempty` tag) or suffix the Meta tag with `,omitempty` (in which case the fields won't be present in both cases when the values are nil).

Now I did notice a bug that might be confusing the issue: the data structure on the server side seems to be using the same custom tag on both fields:
```go
type GetFamResponseBody struct {
	Surname *string               `form:"surname,omitempty" json:"surname,omitempty" xml:"surname,omitempty"`
	Size    *int                  `form:"size,omitempty" json:"size,omitempty" xml:"size,omitempty"`
	Mother  *PersonResponseBody   `json:"mom"`
	Father  *PersonResponseBody   `json:"mom"`
	Kids    []*PersonResponseBody `form:"kids,omitempty" json:"kids,omitempty" xml:"kids,omitempty"`
}
```
I will look into the above.

**Comment by raphael** [comment] 2021-10-25 06:11
The issue described in my comment above has been fixed in #2943

**Comment by lockwobr** [comment] 2021-10-25 20:20
@raphael that was very helpful, that bug was part of the issue we were running into. I think we started to add tags because we noticed in service code it added struct tags there, and we were using that struct for database access, which we might want to not do that for other reasons, but that this could also be a bug, or that is also by design not sure.
https://github.com/lockwobr/goa-example-multi-type/blob/master/pkg/gen/exmp/service.go#L41-L47

**Comment by raphael** [comment] 2021-12-07 00:55
This behavior is by design. We could introduce separate metadata for the service and transport types but so far keeping it simple and the same hasn't been a showstopper (i.e., there hasn't been a case where the tags would have to be different for both types which would be very strange).

**Comment by raphael** [comment] 2022-01-13 17:26
Closing this issue for now.

**Closed as completed by raphael** 2022-01-13 17:26 UTC
