### ISSUE TITLE
ConvertTo ConvertFrom not generating any code in v3.8.2

### ISSUE THREAD

**Issue by sherodtaylor** [goadesign/goa#3128] opened 2022-08-22 16:52 UTC
I have an api design like below. I've added the `ConvertTo` and `CreateFrom` but no new methods are generated

```go
var _ = API("api", func() {
	Title("API")
	Description("some api")
})
var _ = Service("SomeService", func() {
	Description("Service")

	Method("someMethod", func() {
		Payload(Payload)

		Result(Response)

		Error("validation_errors", ValidationResponse)
		Error("unauthorized", UnauthorizedError)

		HTTP(func() {
			POST("/api/v2/do/something")
			Response(StatusAccepted, func() {
				Body(func() {
					Attribute("id", String, "id")
				})
			})
			Response(StatusBadRequest, "validation_errors")
			Response(StatusUnauthorized, "unauthorized")
		})
	})
  // I'm trying to reference an external type here and its not generating any new code to convert to or from that type

  var ValidationError = ResultType("ValidationError", func() {
	ConvertTo(domain.ValidationError{}) // added this and no new code is generated
	CreateFrom(domain.ValidationError{})
	Attribute("message", String, func() {
		Description("error message")
		Example("missing item id")
		Meta("struct.field.external", "Message")
	})
	Attribute("attribute", String, func() {
		Description("attribute that is the issue")
		Example("item_id")
		Meta("struct.field.external", "Attribute")
	})
	Attribute("remediation", String, func() {
		Description("how to resolve error")
		Example("add item_id to payload")
		Meta("struct.field.external", "Remediation")
	})

	Required("message")
})


 ```

**Comment by raphael** [comment] 2022-08-22 22:48
Looks like the design is missing a few pieces (e.g. `ValidationResponse` and `SomeService` isn't formatted right (missing closing brace and parenthesis). Are you able to provide a functional design that reproduces the issue? thanks!

**Closed as not planned** 2022-10-30 05:43 UTC
Labels: no-issue-activity
