### ISSUE TITLE
How to generate bson struct tag by default similar to json and xml?

### ISSUE THREAD

**Issue by dtravin** [goadesign/goa#1045] opened 2017-02-09 10:35 UTC
I have implemented a straightforward solution. 
https://github.com/LiflandGaming/goa

Any better ideas?

**Comment by raphael** [comment] 2017-02-09 21:48
You can use [Metadata](https://goa.design/reference/goa/design/apidsl/#func-metadata-a-name-apidsl-metadata-a) to set the generated struct field tags. Also if it's too cumbersome to have to set Metadata on every field you can create your own DSL function that wraps `Attribute` and attaches metadata to the attribute. Something like (I have not even tried to compile the code below - this is pseudo code just to illustrate the idea):

```go
func BSONAttribute(name string, args ...interface{}) {
    dsl := func() { Metadata("struct:tag:bson", name) }
    if len(args) > 0 {
        if d, ok := args[len(args)-1].(func()); ok {
            mdsl := dsl
            dsl = func() { d(); mdsl() }
            args = args[:len(args)-1]
        }
    }
    args = append(args, dsl)
    Attribute(name, args...)
}
```

**Comment by raphael** [comment] 2017-02-22 04:24
Closing this for now, open a new issue if that does not work or you have follow up questions.

**Closed by raphael** 2017-02-22 04:24 UTC

**Comment by saniales** [comment] 2018-09-06 06:31
#Big Thanks

I can confirm this works, but is it possible to think to integrate a global way to add a metadata to all fields?

**Comment by raphael** [comment] 2018-09-06 16:14
There's a trade-off here between adding more to the language and making things convenient. I haven't heard this request a lot so at this point given the easy workaround I would be hesitant to add yet more DSL for what seems to be a corner case (understand that for you it probably doesn't feel that way).
