### ISSUE TITLE
Client package: Why does it require the paths?

### ISSUE THREAD

**Issue by brasilikum** [goadesign/goa#389] opened 2016-04-06 07:05 UTC
The paths could just be generated from the routing params. 
What is the motivation behind requiring them for every request?
What would you say about an optional path, with the default being generated from the dsl?

**Comment by raphael** [comment] 2016-04-06 15:23
This keeps coming up so it probably makes sense to at least have both options. The rationale for using paths is that it's what is documented (pretty much all API docs are organized by request paths). So taking parameters instead means that as a user you need to reverse engineer the path into the corresponding parameters. Now this mostly applies to the CLI, it would make sense for the package to have functions that allow creating the path from the parameters for all requests.

**Comment by raphael** [comment] 2016-04-06 15:23
Closing this as duplicate of #226

**Closed** 2016-04-06 15:23 UTC
